### ISSUE TITLE
Add copyright to all source files

### ISSUE THREAD

**Issue by AlexanderSoroka** [PavelKovalets/k52#1]

**Comment by PavelKovalets** [comment]
Necessary to have a tool that will do the check automatically

**Comment by AlexanderSoroka** [comment]
see #2

**Comment by PavelKovalets** [comment]
We should determine if it is necessary or not before implementing this

**Comment by PavelKovalets** [comment]
http://licenseit.ru/wiki/index.php/MIT_License

**Comment by PavelKovalets** [comment]
How to apply to their work:

To make your work distributed under the terms of this license must be attached to it the text of the license.
We recommend this to create a file with the name license.txt license and place the text in it. The file is placed in the root directory of the distributed work.
This is done, no additional steps required
